apiVersion: v1 
kind: Pod 
metadata:
  name: nginx
  namespace: rokhnamespace
  labels: 
    app.kubernetes.io/name: nginx
    app: nginx
spec:
  containers:
    - name: web
      image: nginx:1.18
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

    - name: db
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
        - name: MYSQL_DATABASE
          value: 'rokhDB'
 
  initContainers:
    - name: nginx-init-container
      image: busybox
      command: ["/bin/sh", "-c", "echo 'nginx init container'"]
