apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeaffinitydep
  name: nodeaffinitydep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeaffinitydep
  template:
    metadata:
      labels:
        app: nodeaffinitydep
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: enviroment
                  operator: In
                  values:
                  - prod
      containers:
      - image: nginx
        name: nginx
