apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: rokhnamespace
  labels:
    app: nginx
spec:
  replicas: 5

  updateStrategy:
    type: OnDelete 

  serviceName: "nginx"

  podManagementPolicy: OrderedReady 

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx

spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
    - port: 80
      name: web

