# I made this yaml file with this command
# kubectl create job myjob --image=busybox --dry-run=client -o yaml > myjob.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - image: busybox:latest
        name: myjob
        command:
          - 'expr'
          - '10'
          - '*'
          - '10' 
      restartPolicy: Never
