apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: livenessdep
  name: livenessdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livenessdep
  template:
    metadata:
      labels:
        app: livenessdep
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command:
          - /bin/bash
          - -c
          - touch /tmp/prob && sleep infinity

        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/probi
          # Number of seconds after the container has started before liveness probes are initiated.
          initialDelaySeconds: 5
          # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
          periodSeconds: 5
          # Minimum consecutive successes for the probe to be considered successful after having failed.
          successThreshold: 1
          # Number of seconds after which the probe times out.
          timeoutSeconds: 4
