apiVersion: v1
kind: Service
metadata:
  labels:
    app: testservice
  name: testservice
  namespace: default 
spec:
  clusterIP: 10.106.121.183
  clusterIPs:
  - 10.106.121.183
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test 
  sessionAffinity: None
  type: ClusterIP
