apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: psql
  name: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - image: postgres:16.11-alpine3.23
        name: postgres
        envFrom:
          - secretRef:
              name: mysecret 
