apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: nginx
  namespace: rokh
  labels:
    app: nginx-deamonset-lable

spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels: 
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:1.18

